// T050 — Worker spawn guard (NFR-002a, Constitution XII).
// Source of truth: contracts/egress-hook-api.md §"Worker-thread guard contract"
//
// `spawnGuardedWorker(filename, opts?)` ensures every Worker has the runtime
// egress hook installed before any user code runs. We achieve this by
// passing the user's filename via workerData and using a fixed entry script
// that:
//   1. imports the egress-hook-bootstrap (installs the hook synchronously)
//   2. dynamically imports the user's filename
//
// Direct `new Worker(...)` outside this helper is rejected by the
// `no-direct-worker-spawn` lint rule (T025 / NFR-002).

import { Worker, type WorkerOptions } from 'node:worker_threads';
import { fileURLToPath, pathToFileURL } from 'node:url';
import * as path from 'node:path';
import * as fs from 'node:fs';
import { Paths } from '@llm-corpus/contracts/paths';

interface GuardedWorkerData {
  __corpusGuardedUserScript: string;
  userData?: unknown;
}

/**
 * Locate the worker-bootstrap module. Prefer the compiled `.js` from `dist/`
 * (deterministic, no loader required); fall back to the `.ts` source when the
 * package hasn't been built (tests, development). The Worker process gets
 * `--import tsx` injected in execArgv, so the `.ts` fallback also works under
 * the project's TypeScript runtime.
 */
function resolveBootstrapPath(): string {
  const here = fileURLToPath(import.meta.url);
  const dir = path.dirname(here);
  // When running via tsx from src/, dir = packages/daemon/src/
  // When running compiled from dist/, dir = packages/daemon/dist/
  const isDist = path.basename(dir) === 'dist';
  if (isDist) {
    return path.join(dir, 'worker-bootstrap.js');
  }
  // src layout — prefer compiled bootstrap if available (more reliable across
  // worker_threads loader propagation), else use the .ts source.
  const compiled = path.resolve(dir, '..', 'dist', 'worker-bootstrap.js');
  if (fs.existsSync(compiled)) return compiled;
  return path.join(dir, 'worker-bootstrap.ts');
}

/**
 * Generate a tiny on-disk wrapper script. The wrapper imports the egress-hook
 * bootstrap synchronously (via top-level await of dynamic import), then loads
 * the user's worker script. We write to os.tmpdir() and let the OS clean it
 * up; the script is deterministic per-call.
 */
function buildWrapperScript(userFilename: string): string {
  const bootstrapUrl = pathToFileURL(resolveBootstrapPath()).href;
  const userUrl = pathToFileURL(path.resolve(userFilename)).href;
  // Constitution XIV: scratch directory routes through Paths.cache(); we don't
  // use os.tmpdir() because path literals outside the resolver are forbidden.
  const wrapperRoot = path.join(Paths.cache(), 'worker-wrappers');
  fs.mkdirSync(wrapperRoot, { recursive: true });
  const wrapperDir = fs.mkdtempSync(path.join(wrapperRoot, 'wrap-'));
  const wrapperPath = path.join(wrapperDir, 'worker-entry.mjs');
  const content = `
// Auto-generated by spawnGuardedWorker — installs egress hook then runs user script.
await import(${JSON.stringify(bootstrapUrl)});
await import(${JSON.stringify(userUrl)});
`;
  fs.writeFileSync(wrapperPath, content, 'utf8');
  return wrapperPath;
}

export function spawnGuardedWorker(
  filename: string,
  opts: WorkerOptions = {},
): Worker {
  const wrapperPath = buildWrapperScript(filename);
  // tsx is the project's TS runtime loader; --import tsx lets the bootstrap
  // (`worker-bootstrap.ts`) load. If the project ships compiled .js files in
  // dist/, the bootstrap should resolve to .js and tsx is unused but harmless.
  const guardedExecArgv = ['--import', 'tsx', ...(opts.execArgv ?? [])];

  // Pass user-supplied workerData under a sub-key so we don't collide.
  const guardedWorkerData: GuardedWorkerData = {
    __corpusGuardedUserScript: filename,
    userData: opts.workerData as unknown,
  };

  return new Worker(wrapperPath, {
    ...opts,
    execArgv: guardedExecArgv,
    workerData: guardedWorkerData,
  });
}
